
###
// Register
POST http://codeserver.hopto.org:5000/api/auth/register
Content-Type: application/json

{
    "username": "ahmed",
    "password": "passwdwd",
    "email": "ahmed@email.com"
}

###
// Login
POST http://codeserver.hopto.org:5000/api/auth/login
###

// Forgot Password
POST http://codeserver.hopto.org:5000/api/auth/forgotPassword
###

// Reset Password
PUT http://codeserver.hopto.org:5000/api/auth/resetPassword/token

